inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-rails

require:
  - rubocop-capybara
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/*.rb'
    - 'config/*.rb'

RSpec/IndexedLet:
  Enabled: false