# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/locker_applications', type: :request do
  let(:user) { FactoryBot.create :user }
  before do
    sign_in user
  end

  # LockerApplication. As you add validations to LockerApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      LockerApplication.create! valid_attributes
      get locker_applications_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      locker_application = LockerApplication.create! valid_attributes
      get locker_application_url(locker_application)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_locker_application_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      locker_application = LockerApplication.create! valid_attributes
      get edit_locker_application_url(locker_application)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new LockerApplication' do
        expect do
          post locker_applications_url, params: { locker_application: valid_attributes }
        end.to change(LockerApplication, :count).by(1)
      end

      it 'redirects to the created locker_application' do
        post locker_applications_url, params: { locker_application: valid_attributes }
        expect(response).to redirect_to(locker_application_url(LockerApplication.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new LockerApplication' do
        expect do
          post locker_applications_url, params: { locker_application: invalid_attributes }
        end.to change(LockerApplication, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post locker_applications_url, params: { locker_application: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested locker_application' do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: new_attributes }
        locker_application.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the locker_application' do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: new_attributes }
        locker_application.reload
        expect(response).to redirect_to(locker_application_url(locker_application))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested locker_application' do
      locker_application = LockerApplication.create! valid_attributes
      expect do
        delete locker_application_url(locker_application)
      end.to change(LockerApplication, :count).by(-1)
    end

    it 'redirects to the locker_applications list' do
      locker_application = LockerApplication.create! valid_attributes
      delete locker_application_url(locker_application)
      expect(response).to redirect_to(locker_applications_url)
    end
  end
end
