# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/locker_applications', type: :request do
  let(:user) { FactoryBot.create :user }
  before do
    sign_in user
  end

  # LockerApplication. As you add validations to LockerApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      preferred_size: 2,
      preferred_general_area: 'Preferred General Area',
      accessible: false,
      semester: 'Semester',
      status_at_application: 'Status At Application',
      department_at_application: 'Department At Application',
      user_id: user.id
    }
  end

  let(:valid_form_attributes) do
    {
      preferred_size: 2,
      preferred_general_area: 'Preferred General Area',
      accessible: false,
      semester: 'Semester',
      status_at_application: 'Status At Application',
      department_at_application: 'Department At Application',
      user_uid: user.uid
    }
  end

  let(:invalid_attributes) do
    {
      preferred_size: 2,
      preferred_general_area: 'Preferred General Area',
      accessible: false,
      semester: 'Semester',
      status_at_application: 'Status At Application',
      department_at_application: 'Department At Application',
      user_id: nil
    }
  end

  let(:invalid_form_attributes) do
    {
      preferred_size: 2,
      preferred_general_area: 'Preferred General Area',
      accessible: false,
      semester: 'Semester',
      status_at_application: 'Status At Application',
      department_at_application: 'Department At Application',
      user_uid: nil
    }
  end

  describe 'GET /index' do
    it 'redirects to root' do
      LockerApplication.create! valid_attributes
      get locker_applications_url
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'GET /show' do
    it 'Shows the user their application' do
      locker_application = LockerApplication.create! valid_attributes
      get locker_application_url(locker_application)
      expect(response).to be_successful
    end

    context "another's application" do
      before do
        valid_attributes[:user_id] = FactoryBot.create(:user).id
      end
      it 'redirects to root' do
        locker_application = LockerApplication.create! valid_attributes
        get locker_application_url(locker_application)
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'GET /new' do
    it 'allows a user to apply for a locker' do
      get new_locker_application_url
      expect(response).to be_successful
    end
  end

  describe 'GET /assign' do
    it 'redirects to root' do
      locker_application = LockerApplication.create! valid_attributes
      get assign_locker_application_url(locker_application)
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'GET /edit' do
    it 'redirects to root' do
      locker_application = LockerApplication.create! valid_attributes
      get edit_locker_application_url(locker_application)
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'POST /create' do
    context 'creates an application for the user' do
      it 'redirects to root' do
        expect do
          post locker_applications_url, params: { locker_application: valid_form_attributes }
        end.to change(LockerApplication, :count).by(1)
      end

      it 'Shows the user their application' do
        post locker_applications_url, params: { locker_application: valid_form_attributes }
        expect(response).to redirect_to(locker_application_url(LockerApplication.last))
      end

      context "another's application" do
        before do
          valid_form_attributes[:user_uid] = FactoryBot.create(:user).uid
        end
        it 'redirects to root' do
          expect do
            post locker_applications_url, params: { locker_application: valid_form_attributes }
          end.to change(LockerApplication, :count).by(0)
          expect(response).to redirect_to(root_path)
        end
      end
    end

    context 'with invalid parameters' do
      it 'redirects to root' do
        expect do
          post locker_applications_url, params: { locker_application: invalid_form_attributes }
        end.to change(LockerApplication, :count).by(0)
        expect(response).to redirect_to(root_path)
      end

      it 'redirects to root' do
        post locker_applications_url, params: { locker_application: invalid_form_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          preferred_size: 4,
          preferred_general_area: 'Preferred General Area two',
          accessible: false,
          semester: 'Semester',
          status_at_application: 'Status At Application',
          department_at_application: 'Department At Application',
          user_uid: user.uid
        }
      end

      it 'redirects to root and does not update the data' do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: new_attributes }
        locker_application.reload
        expect(locker_application.preferred_size).to eq(2)
        expect(locker_application.preferred_general_area).to eq('Preferred General Area')
      end

      it 'redirects to root' do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: new_attributes }
        locker_application.reload
        expect(response).to redirect_to(root_path)
      end
    end

    context 'with invalid parameters' do
      it 'redirects to root' do
        locker_application = LockerApplication.create! valid_attributes
        patch locker_application_url(locker_application), params: { locker_application: invalid_form_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'redirects to root' do
      locker_application = LockerApplication.create! valid_attributes
      expect do
        delete locker_application_url(locker_application)
      end.to change(LockerApplication, :count).by(0)
      expect(response).to redirect_to(root_path)
    end

    it 'redirects to root' do
      locker_application = LockerApplication.create! valid_attributes
      delete locker_application_url(locker_application)
      expect(response).to redirect_to(root_path)
    end
  end

  context 'with an admin user' do
    let(:user) { FactoryBot.create :user, :admin }

    describe 'GET /index' do
      it 'renders a successful response' do
        LockerApplication.create! valid_attributes
        get locker_applications_url
        expect(response).to be_successful
      end
    end

    describe 'GET /show' do
      it 'renders a successful response' do
        locker_application = LockerApplication.create! valid_attributes
        get locker_application_url(locker_application)
        expect(response).to be_successful
      end
    end

    describe 'GET /new' do
      it 'renders a successful response' do
        get new_locker_application_url
        expect(response).to be_successful
      end
    end

    describe 'GET /edit' do
      it 'render a successful response' do
        locker_application = LockerApplication.create! valid_attributes
        get edit_locker_application_url(locker_application)
        expect(response).to be_successful
      end
    end

    describe 'POST /create' do
      context 'with valid parameters' do
        it 'creates a new LockerApplication' do
          expect do
            post locker_applications_url, params: { locker_application: valid_form_attributes }
          end.to change(LockerApplication, :count).by(1)
        end

        it 'redirects to the created locker_application' do
          post locker_applications_url, params: { locker_application: valid_form_attributes }
          expect(response).to redirect_to(locker_application_url(LockerApplication.last))
        end

        context "another's application" do
          before do
            valid_form_attributes[:user_uid] = FactoryBot.create(:user).uid
          end
          it 'creates a new LockerApplication' do
            expect do
              post locker_applications_url, params: { locker_application: valid_form_attributes }
            end.to change(LockerApplication, :count).by(1)
          end
        end
      end

      context 'with invalid parameters' do
        it 'does not create a new LockerApplication' do
          expect do
            post locker_applications_url, params: { locker_application: invalid_form_attributes }
          end.to change(LockerApplication, :count).by(0)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post locker_applications_url, params: { locker_application: invalid_form_attributes }
          expect(response).to be_unprocessable
        end
      end
    end

    describe 'PATCH /update' do
      context 'with valid parameters' do
        let(:new_attributes) do
          {
            preferred_size: 4,
            preferred_general_area: 'Preferred General Area Two',
            accessible: false,
            semester: 'Semester',
            status_at_application: 'Status At Application',
            department_at_application: 'Department At Application',
            user_uid: user.uid
          }
        end

        it 'updates the requested locker_application' do
          locker_application = LockerApplication.create! valid_attributes
          patch locker_application_url(locker_application), params: { locker_application: new_attributes }
          locker_application.reload
          expect(locker_application.preferred_size).to eq(4)
          expect(locker_application.preferred_general_area).to eq('Preferred General Area Two')
        end

        it 'redirects to the locker_application' do
          locker_application = LockerApplication.create! valid_attributes
          patch locker_application_url(locker_application), params: { locker_application: new_attributes }
          locker_application.reload
          expect(response).to redirect_to(locker_application_url(locker_application))
        end
      end

      context 'with invalid parameters' do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          locker_application = LockerApplication.create! valid_attributes
          patch locker_application_url(locker_application), params: { locker_application: invalid_form_attributes }
          expect(response).to be_unprocessable
        end
      end
    end

    describe 'DELETE /destroy' do
      it 'destroys the requested locker_application' do
        locker_application = LockerApplication.create! valid_attributes
        expect do
          delete locker_application_url(locker_application)
        end.to change(LockerApplication, :count).by(-1)
      end

      it 'redirects to the locker_applications list' do
        locker_application = LockerApplication.create! valid_attributes
        delete locker_application_url(locker_application)
        expect(response).to redirect_to(locker_applications_url)
      end
    end

    describe 'GET /assign' do
      it 'allows an admin to assign a locker' do
        locker_application = LockerApplication.create! valid_attributes
        get assign_locker_application_url(locker_application)
        expect(response).to be_successful
      end
    end

    describe 'GET /awaiting_assignment' do
      it 'allows an admin to assign a locker' do
        LockerApplication.create! valid_attributes
        get awaiting_assignment_locker_applications_url
        expect(response).to be_successful
      end
    end
  end
end
