# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/study_rooms', type: :request do
  let(:user) { FactoryBot.create :user }

  # StudyRoom. As you add validations to StudyRoom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { location: 'location', general_area: 'area', notes: 'note' } }

  let(:invalid_attributes) { { location: nil, general_area: nil, notes: 'note' } }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'redirects to root' do
      StudyRoom.create! valid_attributes
      get study_rooms_url
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'GET /show' do
    it 'redirects to root' do
      study_room = StudyRoom.create! valid_attributes
      get study_room_url(study_room)
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'GET /new' do
    it 'redirects to root' do
      get new_study_room_url
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'GET /edit' do
    it 'redirects to root' do
      study_room = StudyRoom.create! valid_attributes
      get edit_study_room_url(study_room)
      expect(response).to redirect_to(root_path)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'does not create a new StudyRoom' do
        expect do
          post study_rooms_url, params: { study_room: valid_attributes }
        end.not_to change(StudyRoom, :count)
      end

      it 'redirects to root' do
        post study_rooms_url, params: { study_room: valid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new StudyRoom' do
        expect do
          post study_rooms_url, params: { study_room: invalid_attributes }
        end.not_to change(StudyRoom, :count)
      end

      it 'redirects to root' do
        post study_rooms_url, params: { study_room: invalid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'redirects to root' do
        study_room = StudyRoom.create! valid_attributes
        patch study_room_url(study_room), params: { study_room: new_attributes }
        study_room.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to root' do
        study_room = StudyRoom.create! valid_attributes
        patch study_room_url(study_room), params: { study_room: new_attributes }
        study_room.reload
        expect(response).to redirect_to(root_path)
      end
    end

    context 'with invalid parameters' do
      it 'redirects to root' do
        study_room = StudyRoom.create! valid_attributes
        patch study_room_url(study_room), params: { study_room: invalid_attributes }
        expect(response).to redirect_to(root_path)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'does not destroy the requested study_room' do
      study_room = StudyRoom.create! valid_attributes
      expect do
        delete study_room_url(study_room)
      end.not_to change(StudyRoom, :count)
    end

    it 'redirects to root' do
      study_room = StudyRoom.create! valid_attributes
      delete study_room_url(study_room)
      expect(response).to redirect_to(root_path)
    end
  end

  context 'with an admin user' do
    let(:user) { FactoryBot.create :user, :admin }

    describe 'GET /index' do
      it 'renders a successful response' do
        StudyRoom.create! valid_attributes
        get study_rooms_url
        expect(response).to be_successful
      end
    end

    describe 'GET /show' do
      it 'renders a successful response' do
        study_room = StudyRoom.create! valid_attributes
        get study_room_url(study_room)
        expect(response).to be_successful
      end
    end

    describe 'GET /new' do
      it 'renders a successful response' do
        get new_study_room_url
        expect(response).to be_successful
      end
    end

    describe 'GET /edit' do
      it 'render a successful response' do
        study_room = StudyRoom.create! valid_attributes
        get edit_study_room_url(study_room)
        expect(response).to be_successful
      end
    end

    describe 'POST /create' do
      context 'with valid parameters' do
        it 'creates a new StudyRoom' do
          expect do
            post study_rooms_url, params: { study_room: valid_attributes }
          end.to change(StudyRoom, :count).by(1)
        end

        it 'redirects to the created study_room' do
          post study_rooms_url, params: { study_room: valid_attributes }
          expect(response).to redirect_to(study_room_url(StudyRoom.last))
        end
      end

      context 'with invalid parameters' do
        it 'does not create a new StudyRoom' do
          expect do
            post study_rooms_url, params: { study_room: invalid_attributes }
          end.not_to change(StudyRoom, :count)
        end

        it "renders a successful response (i.e. to display the 'new' template)" do
          post study_rooms_url, params: { study_room: invalid_attributes }
          expect(response).to be_unprocessable
        end
      end
    end

    describe 'PATCH /update' do
      context 'with valid parameters' do
        let(:new_attributes) do
          skip('Add a hash of attributes valid for your model')
        end

        it 'updates the requested study_room' do
          study_room = StudyRoom.create! valid_attributes
          patch study_room_url(study_room), params: { study_room: new_attributes }
          study_room.reload
          skip('Add assertions for updated state')
        end

        it 'redirects to the study_room' do
          study_room = StudyRoom.create! valid_attributes
          patch study_room_url(study_room), params: { study_room: new_attributes }
          study_room.reload
          expect(response).to redirect_to(study_room_url(study_room))
        end
      end

      context 'with invalid parameters' do
        it "renders a successful response (i.e. to display the 'edit' template)" do
          study_room = StudyRoom.create! valid_attributes
          patch study_room_url(study_room), params: { study_room: invalid_attributes }
          expect(response).to be_unprocessable
        end
      end
    end

    describe 'DELETE /destroy' do
      it 'destroys the requested study_room' do
        study_room = StudyRoom.create! valid_attributes
        expect do
          delete study_room_url(study_room)
        end.to change(StudyRoom, :count).by(-1)
      end

      it 'redirects to the study_rooms list' do
        study_room = StudyRoom.create! valid_attributes
        delete study_room_url(study_room)
        expect(response).to redirect_to(study_rooms_url)
      end
    end
  end
end
